name: Build FrankenPHP binaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  # Allow manual triggering
  schedule:
    - cron: '0 0 * * 0'  # Weekly builds on Sunday at midnight

# Add explicit permissions for creating GitHub releases
permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        php-version: ['8.3.20', '8.4.6']  # Latest 8.3 stable and 8.4 stable
        include:
          - php-version: '8.3.20'
            php-short: 'php83'
          - php-version: '8.4.6'
            php-short: 'php84'
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest FrankenPHP version
        id: frankenphp_version
        run: |
          # Install jq if not already installed
          sudo apt-get update
          sudo apt-get install -y jq
          
          # Use GitHub API to get the latest release
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/dunglas/frankenphp/releases/latest | jq -r '.tag_name')
          # Remove the 'v' prefix if present
          FRANKENPHP_VERSION=${LATEST_RELEASE#v}
          echo "FRANKENPHP_VERSION=$FRANKENPHP_VERSION" >> $GITHUB_ENV
          echo "Latest FrankenPHP version: $FRANKENPHP_VERSION"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl ca-certificates \
            pkg-config libssl-dev zlib1g-dev libxml2-dev libbrotli-dev \
            autoconf automake libtool libsqlite3-dev libcurl4-openssl-dev libonig-dev \
            libmariadb-dev libmariadb-dev-compat

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: false

      - name: Get PHP ${{ matrix.php-version }}
        run: |
          curl -L https://www.php.net/distributions/php-${{ matrix.php-version }}.tar.gz -o php.tar.gz
          tar xf php.tar.gz

      - name: Configure and Build PHP
        run: |
          cd php-${{ matrix.php-version }}/
          # Using the exact flags recommended for Linux in the FrankenPHP documentation
          ./configure \
            --enable-embed \
            --enable-zts \
            --disable-zend-signals \
            --enable-zend-max-execution-timers \
            --enable-mbstring \
            --with-openssl \
            --enable-xml \
            --enable-ctype \
            --with-curl \
            --enable-dom \
            --enable-fileinfo \
            --enable-filter \
            --enable-hash \
            --enable-pdo \
            --with-pdo-sqlite \
            --with-pdo-mysql \
            --with-mysqli \
            --enable-session \
            --enable-tokenizer
          make -j$(nproc)
          sudo make install
          sudo ldconfig

      - name: Get FrankenPHP
        run: |
          curl -L https://github.com/dunglas/frankenphp/archive/refs/tags/v${FRANKENPHP_VERSION}.tar.gz | tar xz

      - name: Build FrankenPHP
        working-directory: frankenphp-${{ env.FRANKENPHP_VERSION }}/caddy/frankenphp
        run: |
          # Using the exact approach recommended in the FrankenPHP documentation
          CGO_CFLAGS=$(php-config --includes) CGO_LDFLAGS="$(php-config --ldflags) $(php-config --libs)" go build -tags=nobadger,nomysql,nopgx

      - name: Test binary
        run: |
          echo "Checking binary details..."
          frankenphp-${FRANKENPHP_VERSION}/caddy/frankenphp/frankenphp version

      - name: Package FrankenPHP Binary
        run: |
          # Create directory
          mkdir -p dist
          
          # Copy the FrankenPHP binary
          cp frankenphp-${FRANKENPHP_VERSION}/caddy/frankenphp/frankenphp dist/
          chmod +x dist/frankenphp
          
          # Create archive with just the binary
          cd dist
          tar -czf ../frankenphp-linux-amd64-${{ matrix.php-short }}.tar.gz frankenphp
          cd ..

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: frankenphp-${{ matrix.php-short }}
          path: frankenphp-linux-amd64-${{ matrix.php-short }}.tar.gz
          retention-days: 7

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        with:
          tag_name: v${{ env.FRANKENPHP_VERSION }}-${{ matrix.php-short }}-${{ github.run_number }}
          name: FrankenPHP v${{ env.FRANKENPHP_VERSION }} with PHP ${{ matrix.php-version }}
          draft: false
          prerelease: false
          files: frankenphp-linux-amd64-${{ matrix.php-short }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
