name: Build FrankenPHP with PHP 8.3

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl ca-certificates \
            pkg-config libssl-dev zlib1g-dev libxml2-dev libbrotli-dev \
            autoconf automake libtool libsqlite3-dev libcurl4-openssl-dev libonig-dev

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Get PHP 8.3
        run: |
          curl -L https://www.php.net/distributions/php-8.3.5.tar.gz -o php.tar.gz
          tar xf php.tar.gz

      - name: Configure and Build PHP
        run: |
          cd php-8.3.5/
          ./configure \
            --enable-embed \
            --enable-zts \
            --disable-zend-signals \
            --enable-zend-max-execution-timers
          make -j$(nproc)
          sudo make install
          sudo ldconfig

      - name: Get FrankenPHP
        run: |
          curl -L https://github.com/dunglas/frankenphp/archive/refs/tags/v1.1.2.tar.gz | tar xz

      - name: Build FrankenPHP
        run: |
          cd frankenphp-1.1.2/caddy/frankenphp
          CGO_CFLAGS=$(php-config --includes) CGO_LDFLAGS="$(php-config --ldflags) $(php-config --libs)" go build -tags=nobadger,nomysql,nopgx

      - name: Copy PHP library dependencies
        run: |
          # Find libphp.so and copy to a directory we'll package
          mkdir -p dist/lib
          cp $(php-config --prefix)/lib/libphp.so dist/lib/
          # Copy all other dependencies
          ldd frankenphp-1.1.2/caddy/frankenphp/frankenphp | grep "=> /" | awk '{print $3}' | grep -v "libc.so" | grep -v "ld-linux" | xargs -I '{}' cp -v '{}' dist/lib/
          # Copy the binary
          cp frankenphp-1.1.2/caddy/frankenphp/frankenphp dist/

      - name: Create wrapper script
        run: |
          cat > dist/run-frankenphp.sh << 'EOF'
          #!/bin/bash
          SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
          LD_LIBRARY_PATH="$SCRIPT_DIR/lib:$LD_LIBRARY_PATH" "$SCRIPT_DIR/frankenphp" "$@"
          EOF
          chmod +x dist/run-frankenphp.sh

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: frankenphp-php8.3
          path: dist
          retention-days: 7
