name: Build FrankenPHP Latest Release
on:
  workflow_dispatch:  # Allows manual triggering
  
jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release info
        id: get_release
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/dunglas/frankenphp/releases/latest)
          LATEST_VERSION=$(echo $LATEST_RELEASE | jq -r .tag_name)
          echo "Latest FrankenPHP release: $LATEST_VERSION"
          echo "tag_name=$LATEST_VERSION" >> $GITHUB_OUTPUT
      
      - name: Checkout FrankenPHP
        uses: actions/checkout@v4
        with:
          repository: dunglas/frankenphp
          ref: ${{ steps.get_release.outputs.tag_name }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build FrankenPHP static binary
        run: |
          # Create a specific context for the static builder
          mkdir -p dist
          
          # Build the static builder image
          docker build --target static-builder-gnu -t frankenphp-static-builder -f Dockerfile .
          
          # Create a container from the static builder image
          CONTAINER_ID=$(docker create frankenphp-static-builder)
          
          # Copy the binary from the container
          docker cp $CONTAINER_ID:/go/src/app/dist/frankenphp-linux-$(uname -m) dist/frankenphp
          
          # Remove the container
          docker rm $CONTAINER_ID
          
          # Make the binary executable
          chmod +x dist/frankenphp
          
          # Display version info
          if [ -f "dist/frankenphp" ]; then
            dist/frankenphp version || echo "Binary built, but couldn't display version info"
          else
            echo "Failed to build FrankenPHP binary"
            exit 1
          fi
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frankenphp-${{ steps.get_release.outputs.tag_name }}
          path: dist/frankenphp
          retention-days: 7
